---
- name: Upgrade the OS
  apt:
    upgrade: dist
  register: upgrade_os
  changed_when: false
  become: true
  become_method: su
- name: Install Curl
  become: true
  become_method: su
  apt:
    name: curl
    state: present
    update_cache: yes
- name: Install Kibana
  become: true
  become_method: su
  apt:
    deb: "/tmp/kibana-{{ kibana_version }}-amd64.deb"
    state: present
